# REQUIRED CHANGES
# Edit next line to provide your own name.
title: Michal Lopasovsky | Technical Artist
# Edit next line, replacing 'techfolios' with your github username
url: "https://michal-lopasovsky.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
bio-page-label: Resume
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
# theme-home: theme-home-builtin-2.html
theme-home: theme-home-ml-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-1.html

# DON'T CHANGE THE FOLLOWING (unless you know what you're doing)
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
